<?php
require_once __DIR__.'/../config/config.php'; start_app_session();
if(empty($_SESSION['player_game_id'])) redirect('/game/login.php');
$st=db()->prepare("SELECT g.*,s.title,s.subtitle,s.slug FROM games g JOIN stories s ON s.id=g.story_id WHERE g.id=?"); $st->execute([$_SESSION['player_game_id']]); $game=$st->fetch(PDO::FETCH_ASSOC); if(!$game) redirect('/game/login.php');
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($game['title'])?> — RT ESCAPE</title><link rel="stylesheet" href="/assets/app.css"></head>
<body class="game-ui rttf-ui"><header class="game-top"><div class="game-logo">RT <span>ESCAPE</span></div><div class="mission">DOSSIER <strong id="stage">01</strong> / 05 <span id="roleBadge" class="role-badge"></span></div><div class="timer-wrap"><small>FENÊTRE TEMPORELLE</small><div class="timer" id="timer">--:--</div></div></header>
<main class="game-main"><section class="scientist"><div class="avatar" id="avatar">⚡</div><div><span class="eyebrow" id="eyebrow">TRANSMISSION ENTRANTE</span><h1 id="title">ANOMALIE TEMPORELLE DÉTECTÉE</h1><p id="story">La ligne temporelle est instable.</p></div></section>
<section class="game-panel"><div class="progress"><i id="progress"></i></div><div id="mission-content" class="mission-content"></div></section></main>
<div class="evidence-modal hidden" id="evidenceModal"><div class="evidence-card"><button class="close-x" onclick="closeEvidence()">×</button><div id="evidenceBody"></div></div></div>
<div class="modal hidden" id="answerModal"><div class="answer-card time-terminal"><span class="eyebrow">TERMINAL DE SYNCHRONISATION</span><div class="terminal-screen"><small>DESTINATION / CODE DE RETOUR</small><strong id="answerDisplay">_ _ _ _ _ _ _ _ _ _</strong></div><p id="answerPrompt">La fenêtre temporelle se referme. Entrez le code sur le clavier de la machine.</p><div class="keypad" id="keypad"></div><button class="btn primary terminal-submit" onclick="submitTerminal()">⚡ ENVOYER À LA MACHINE</button><div id="answerMessage" class="answer-message"></div></div></div>
<div class="toast hidden" id="toast"></div>
<script>
const playerToken=<?=json_encode((string)($_SESSION['player_token']??''),JSON_UNESCAPED_SLASHES)?>;
let state=null,poll=null,lastStage=0,modalForced=false,terminalValue='';
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function fmt(sec){sec=Math.max(0,Number(sec)||0);return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
async function fetchState(){const r=await fetch('/api/state.php?player_token='+encodeURIComponent(playerToken),{cache:'no-store'});if(r.status===410){document.body.innerHTML='<main class="join"><section class="join-card"><span class="eyebrow">ACCÈS COUPÉ</span><h1>Vous avez été retiré</h1><p>L’organisateur a fermé votre accès à cette timeline.</p><a class="btn primary" href="/game/login.php">REJOINDRE UNE AUTRE PARTIE</a></section></main>';clearInterval(poll);return;}if(!r.ok)return;const d=await r.json();if(!d.ok)return;state=d.game;render();}
function render(){
 if(!state)return; const stage=Number(state.stage);document.getElementById('stage').textContent=String(stage||1).padStart(2,'0');document.getElementById('timer').textContent=fmt(state.stage_remaining);document.getElementById('progress').style.width=(stage/5*100)+'%';document.getElementById('timer').classList.toggle('danger',state.stage_remaining<=60);
 if(stage!==lastStage){lastStage=stage;modalForced=false;terminalValue='';} document.getElementById('roleBadge').textContent=state.me&&state.me.role_label?(' · '+state.me.role_label):'';
 if(!stage){
  document.getElementById('title').textContent='PRENEZ PLACE DANS LA DELOREAN';
  document.getElementById('story').textContent='Le professeur vous attend. Votre identité temporelle vous a été attribuée. Rejoignez votre siège dans la salle puis confirmez votre présence.';
  const me=state.me||{}; const crew=state.crew||[]; const readyCount=crew.filter(x=>Number(x.ready)===1).length;
  document.getElementById('roleBadge').textContent=me.role_label?(' · '+me.role_label):' · RÔLE EN ATTENTE';
  const hasRole=!!me.role_key;
  const readyText=me.ready?'✓ POSITION CONFIRMÉE':'JE SUIS EN PLACE';
  document.getElementById('mission-content').innerHTML=`<div class="deLorean-prep">
    <div class="prep-screen"><div class="prep-sky">HILL VALLEY · 1985</div><div class="prep-dashboard"><div class="dash-speed">0 <small>MPH</small></div><div class="dash-flux">⚡<span>FLUX CAPACITOR</span><b>OFFLINE</b></div><div class="dash-time">01:21:00</div></div><div class="prep-windshield"><span>DELOREAN DMC-12</span><strong>READY FOR TEMPORAL DISPLACEMENT</strong></div></div>
    <div class="identity-card"><span class="eyebrow">IDENTITÉ TEMPORAIRE</span><div class="identity-role">${esc(me.role_label||'RÔLE EN ATTENTE')}</div><div class="identity-seat">POSTE : ${esc(me.seat||'À DÉTERMINER')}</div><p>${esc(hasRole?(me.role_key==='driver'?'Tu es responsable du départ. Écoute les autres membres de l’équipage et observe ton poste.':me.role_key==='archivist'?'Tu possèdes des connaissances que les autres n’ont pas. Ne garde pas tes découvertes pour toi.':me.role_key==='technician'?'Tu es le spécialiste des systèmes. Certains mécanismes te reconnaîtront.':me.role_key==='chrononaut'?'Tes instruments surveillent les anomalies temporelles.':me.role_key==='observer'?'Tu dois remarquer ce que personne ne voit.':'Tu as une fonction secrète dans la mission.'):'Le maître du jeu est en train de t’attribuer ton identité. Tu pourras confirmer ta présence dès que ton rôle sera affiché.')}</p><button class="ready-button ${me.ready?'ready':''}" onclick="readyUp()" ${me.ready||!hasRole?'disabled':''}>${hasRole?readyText:'RÔLE EN ATTENTE'}</button><div class="crew-ready">ÉQUIPAGE : ${readyCount} / ${crew.length} EN PLACE</div></div>
    <div class="secret-briefing"><span class="eyebrow">MESSAGE PERSONNEL · NE PAS MONTRER</span><p>${esc(me.secret||'Observez attentivement votre poste et partagez vos découvertes avec l’équipage.')}</p></div><div class="prep-instruction"><span>🎙</span><div><b>ÉCOUTEZ LE MAÎTRE DU JEU</b><small>Votre aventure commencera lorsque tout l’équipage aura pris place. Ne quittez pas votre poste.</small></div></div>
  </div>`;return;}
 if(state.status==='finished'&&stage===5&&state.response_value){document.getElementById('title').textContent='TIMELINE RESTORED';document.getElementById('story').textContent='La ligne temporelle est stabilisée.';document.getElementById('mission-content').innerHTML='<div class="finale cinematic-finale"><div class="lightning-burst">⚡</div><h2>MISSION ACCOMPLIE</h2><p>88 MPH · 1.21 GW · DESTINATION VALIDÉE</p><strong>BON ANNIVERSAIRE LÉANE !</strong><div class="finale-date">HILL VALLEY · 1985</div></div>';return;}
 const m=state.mission;if(!m)return;document.getElementById('eyebrow').textContent=m.eyebrow;document.getElementById('title').textContent=m.title;document.getElementById('story').textContent=m.intro;
 const found=new Set(state.discoveries||[]);let html=renderScene(stage,m,found);if(state.hint)html+='<div class="hint-box cinematic-hint"><strong>MESSAGE DU PROFESSEUR</strong><p>'+esc(state.hint)+'</p></div>';if(state.answer_revealed)html+='<div class="revealed-answer cinematic-reveal"><span>LE PROFESSEUR A TRANSMIS LE CODE</span><strong>'+esc(state.revealed_answer)+'</strong></div>';if(state.response_required)html+='<button class="force-answer cinematic-answer-btn" onclick="openAnswer()">⚡ ACTIVER LE TERMINAL DE RÉPONSE</button>';document.getElementById('mission-content').innerHTML=html;if(state.response_required&&!modalForced)openAnswer();}
function sceneHeader(label,text,found,total){return `<div class="scene-header"><div><span class="eyebrow">${label}</span><h2>${text}</h2></div><div class="found film-counter">${found} / ${total} indices</div></div>`}
function hotspot(key,icon,title,found){return `<button class="scene-hotspot ${found?'found':''}" onclick="inspect('${key}')"><span class="hot-icon">${icon}</span><b>${title}</b><small>${found?'INDICE RÉCUPÉRÉ':'EXAMINER'}</small></button>`}
function controlPanel(title,subtitle,body){return `<div class="control-panel"><div class="control-panel-head"><span class="eyebrow">${title}</span><small>${subtitle}</small></div>${body}</div>`}
function renderScene(stage,m,found){
 const p=state.puzzle||{};
 if(stage===1){
   const role=state.me?.role_key||''; const roleLabel=state.me?.role_label||'MEMBRE DE L’ÉQUIPAGE';
   return `<div class="deLorean-room-player"><div class="cockpit-visual"><div class="windshield-player"><div class="hillvalley">HILL VALLEY</div><div class="night-road"></div><div class="road-lights"></div></div><div class="dashboard-player"><div class="gauge-player"><b>0</b><small>MPH</small></div><div class="flux-player"><span>⚡</span><b>FLUX CAPACITOR</b><small>${esc(state.gm_event||'STANDBY')}</small></div><div class="time-circuit-player"><small>TIME CIRCUIT</small><strong>-- / -- / ----</strong><strong>-- : --</strong></div></div><div class="cabin-lights"></div></div><div class="role-briefing"><span class="eyebrow">VOTRE IDENTITÉ · CONFIDENTIEL</span><h2>${esc(roleLabel)}</h2><p>${esc(state.me?.secret||'Observez votre environnement et échangez avec votre équipage.')}</p><div class="master-rule"><strong>🎙 MAÎTRE DU JEU</strong><span>Cette séquence se joue dans la salle. Écoutez l'histoire, observez la DeLorean et coopérez avec les autres. L'écran ne vous donnera pas la solution.</span></div></div><div class="event-status"><span class="event-dot"></span><span>${esc(state.gm_event==='boarding'?'ÉQUIPAGE EN PLACE · EN ATTENTE DU MAÎTRE DU JEU':state.gm_event==='story_start'?'LE VOYAGE COMMENCE':state.gm_event==='anomaly'?'ANOMALIE TEMPORELLE':state.gm_event==='coordinates'?'COORDONNÉES DÉTECTÉES':state.gm_event==='prepare_jump'?'PRÉPAREZ-VOUS AU SAUT':state.gm_event==='jump'?'SAUT TEMPOREL':'SYSTÈMES EN ACTIVATION')}</span></div></div>`;
 } if(stage===2)return sceneHeader('SCÈNE 02 · ARCHIVES','LES ARCHIVES DE HILL VALLEY',Object.keys(p.opened||{}).length+(p.timeline_ok?1:0)+(p.photo_ok?1:0),5)+`<div class="rttf-room archive-room"><div class="archive-title">HILL VALLEY COUNTY ARCHIVES <small>SECTION TEMPORAL INCIDENTS</small></div><div class="drawer-wall"><button class="drawer" onclick="doAction('archive','newspaper')">📁 JOURNAL 1955</button><button class="drawer" onclick="doAction('archive','incident')">📁 INCIDENT 1985</button><button class="drawer" onclick="doAction('archive','future')">📁 DOSSIER INCONNU</button></div><div class="timeline-table"><h3>TABLEAU CHRONOLOGIQUE</h3><p>Placez les cartes de gauche à droite dans l'ordre où elles doivent exister.</p><div class="sort-cards timeline-cards"><button class="sort-card" onclick="timelinePick('A')">1955</button><button class="sort-card" onclick="timelinePick('B')">1985</button><button class="sort-card" onclick="timelinePick('C')">ANOMALIE</button></div><div class="sequence-display">${(p.timeline||'___').padEnd(3,'_').split('').join(' → ')}</div><button class="lock-btn" onclick="doAction('timeline','${p.timeline||''}')">VALIDER LA CHRONOLOGIE</button></div><div class="photo-lab"><div class="photo-frame" style="transform:rotate(${p.photo_angle||0}deg)">📸<span>POLAROID · HILL VALLEY</span></div><div class="photo-controls"><button onclick="photoRotate(-90)">↶</button><button onclick="photoRotate(90)">↷</button></div><p>Alignez le négatif pour révéler l'inscription.</p></div></div><div class="scene-tip">Les archives sont des objets à manipuler, pas une liste de questions.</div>`;
 if(stage===3)return sceneHeader('SCÈNE 03 · TRANSMISSION','LA RADIO TEMPORELLE',Number(!!p.freq_ok)+Number(!!p.morse_ok)+Number(!!p.tape_ok),3)+`<div class="rttf-room transmission-room"><div class="antenna"></div><div class="radio-console-big"><div class="radio-display-big">${Number(p.freq??87).toFixed(1)} MHz</div><input id="freq3" type="range" min="87" max="90" step="0.1" value="${p.freq??87}"><button class="lock-btn" onclick="doAction('frequency',document.getElementById('freq3').value)">ACCROCHER LE SIGNAL</button><div class="wave-big"><i></i><i></i><i></i><i></i><i></i></div></div><div class="morse-box"><h3>SIGNAL MORSE</h3><p>Les voyants s'allument. Reproduisez la séquence.</p><div class="morse-lights">${[1,2,3,4].map(i=>`<button onclick="morsePick('${i}')">${i}</button>`).join('')}</div><div class="sequence-display">${p.morse||'____'}</div><button class="lock-btn" onclick="doAction('morse','${p.morse||''}')">TRANSMETTRE</button></div><div class="tape-machine"><div class="reel left"></div><div class="reel right"></div><div class="tape-label">BAND 1985 · MESSAGE 01</div><button onclick="doAction('tape','play')">▶ LIRE LA BANDE</button><div class="subtitle-signal">${p.tape_ok?'« SI VOUS M’ENTENDEZ… RENTREZ À 1985. »':'BANDE EN ATTENTE'}</div></div></div>`;
 if(stage===4)return sceneHeader('SCÈNE 04 · DELOREAN','TIME CIRCUIT CONTROL',Object.keys(p).filter(k=>/_ok$/.test(k)).length,6)+`<div class="rttf-room delorean-room"><div class="windshield-view">HILL VALLEY · NIGHT<br><small>RAIN · 88 MPH ZONE</small></div><div class="time-circuit-panel"><div class="circuit-row"><label>YEAR</label><button onclick="cycleSetting('year',['1955','1985','2026'])">${p.year||'----'}</button></div><div class="circuit-row"><label>MONTH</label><button onclick="cycleSetting('month',['09','10','11'])">${p.month||'--'}</button></div><div class="circuit-row"><label>DAY</label><button onclick="cycleSetting('day',['25','26','27'])">${p.day||'--'}</button></div><div class="circuit-row"><label>HOUR</label><button onclick="cycleSetting('hour',['20','21','22'])">${p.hour||'--'}</button></div><div class="circuit-row"><label>MIN</label><button onclick="cycleSetting('minute',['59','00','01'])">${p.minute||'--'}</button></div></div><div class="delorean-ignition"><h3>IGNITION SEQUENCE</h3><button onclick="doAction('ignition','power')">① POWER</button><button onclick="doAction('ignition','brake')">② BRAKE</button><button onclick="doAction('ignition','launch')">③ LAUNCH</button><div class="ignition-led">${p.ignition_ok?'READY TO TRAVEL':'WAITING'}</div></div><div class="dashboard-flux">⚡<strong>FLUX</strong><span>1.21 GW</span></div></div>`;
 return sceneHeader('SCÈNE 05 · FINALE','LE FLUX CAPACITOR',Number((p.power||0)===121)+Number((p.speed||0)===88)+Number(!!p.switch_ok),3)+`<div class="rttf-room finale-room"><div class="final-core"><div class="core-ring"></div><div class="core-text"><span>FLUX CAPACITOR</span><strong>${p.power||0}</strong><small>GW</small></div></div><div class="final-control"><label>PUISSANCE</label><input id="powerSlider" type="range" min="100" max="130" value="${p.power||100}" oninput="document.getElementById('powerVal').textContent=this.value"><strong id="powerVal">${p.power||100}</strong> GW<button class="lock-btn" onclick="doAction('slider','power',{setting:document.getElementById('powerSlider').value})">VERROUILLER 1.21 GW</button></div><div class="speed-control"><label>VITESSE</label><input id="speedSlider" type="range" min="70" max="100" value="${p.speed||70}" oninput="document.getElementById('speedVal').textContent=this.value"><strong id="speedVal">${p.speed||70}</strong> MPH<button class="lock-btn" onclick="doAction('slider','speed',{setting:document.getElementById('speedSlider').value})">VERROUILLER 88 MPH</button></div><div class="final-switchboard"><h3>DERNIÈRE SÉQUENCE</h3><button onclick="doAction('switch','flux')">⚡ FLUX</button><button onclick="doAction('switch','capacitor')">🔋 CAPACITOR</button><button onclick="doAction('switch','speed')">🚗 VITESSE</button><div class="sequence-display">${(p.switches||[]).join(' → ')||'READY'}</div></div></div>`;
}
async function doAction(action,value='',extra={}){const fd=new URLSearchParams({action,value,player_token:playerToken,...extra});const r=await fetch('/api/action.php',{method:'POST',body:fd});const d=await r.json();if(d.ok){if(d.message)toast(d.message);await fetchState();if(d.solved)toast('ÉPREUVE VALIDÉE — ATTENDEZ LA SUITE');}else toast(d.message||'La machine refuse la commande.');}
function clockAdjust(dh,dm){const c=state.puzzle?.clock||{h:10,m:0};let h=(c.h+dh+24)%24,m=(c.m+dm+60)%60;doAction('clock','',{h,m});}
function sortPick(x){let cur=state.puzzle?.files_order||'';cur=cur.includes(x)?cur.replace(x,''):cur+x;if(cur.length>3)cur=cur.slice(-3);doAction('files',cur)}
function timelinePick(x){let cur=state.puzzle?.timeline||'';cur=cur.includes(x)?cur.replace(x,''):cur+x;if(cur.length>3)cur=cur.slice(-3);doAction('timeline',cur)}
function radioPreview(v){const el=document.querySelector('.radio-real .radio-display');if(el)el.innerHTML=Number(v).toFixed(1)+' <small>MHz</small>'}
function consoleKey(x){let seq=state.puzzle?.console_seq||[];seq=[...seq,x].slice(-3);doAction('console',x)}
function photoRotate(d){let a=((Number(state.puzzle?.photo_angle||0)+d)%360+360)%360;doAction('photo',a)}
function morsePick(x){let cur=state.puzzle?.morse||'';cur=(cur+x).slice(-4);doAction('morse',cur)}
function cycleSetting(field,vals){let cur=state.puzzle?.[field]||vals[0];let idx=vals.indexOf(cur);let next=vals[(idx+1)%vals.length];doAction('circuit',field,{setting:next})}
async function inspect(key){const body=new URLSearchParams({key,stage:String(state.stage),player_token:playerToken});const r=await fetch('/api/discover.php',{method:'POST',body});const d=await r.json();if(d.ok){state.discoveries=[...(state.discoveries||[]),d.key].filter((v,i,a)=>a.indexOf(v)===i);openEvidence(d);render();}}
function openEvidence(d){const body=document.getElementById('evidenceBody');body.innerHTML=`<span class="eyebrow">ARCHIVE RÉCUPÉRÉE</span><div class="evidence-object">${esc(d.title)}</div><p>${esc(d.text)}</p><div class="evidence-fragment"><small>FRAGMENT TEMPORAL</small><strong>${esc(d.clue)}</strong></div><div class="evidence-stamp">TEMPORAL RESEARCH · 1985</div>`;document.getElementById('evidenceModal').classList.remove('hidden');}
function closeEvidence(){document.getElementById('evidenceModal').classList.add('hidden')}
function buildKeypad(){const k=document.getElementById('keypad');k.innerHTML='';for(let i=1;i<=9;i++)k.innerHTML+=`<button onclick="keyPress('${i}')">${i}</button>`;k.innerHTML+=`<button class="clear" onclick="keyClear()">CLR</button><button onclick="keyPress('0')">0</button><button class="back" onclick="keyBack()">⌫</button>`;}
function keyPress(v){if(terminalValue.length>=12)return;terminalValue+=v;updateDisplay()}
function keyClear(){terminalValue='';updateDisplay()}
function keyBack(){terminalValue=terminalValue.slice(0,-1);updateDisplay()}
function updateDisplay(){document.getElementById('answerDisplay').textContent=(terminalValue||'_').padEnd(10,'_').split('').join(' ')}
function openAnswer(){buildKeypad();terminalValue='';updateDisplay();document.getElementById('answerModal').classList.remove('hidden');modalForced=true}
async function submitTerminal(){if(!terminalValue)return;const body=new URLSearchParams({stage:String(state.stage),answer:terminalValue,player_token:playerToken});const r=await fetch('/api/answer.php',{method:'POST',body});const d=await r.json();const box=document.getElementById('answerMessage');box.textContent=d.message||'';box.className='answer-message'+(d.correct?'':' error');if(d.correct){document.getElementById('answerModal').classList.add('hidden');toast(d.finished?'TIMELINE RESTORED !':'COORDONNÉES VALIDÉES !');modalForced=false;await fetchState();}}
function tuneRadio(){toast('88.7 MHz — SIGNAL VERROUILLÉ');}
function pulseCore(){toast('Flux capacitor : synchronisation en cours…')}
async function readyUp(){if(!state?.me?.role_key){toast('Le maître du jeu doit d’abord attribuer ton rôle.');return;}const r=await fetch('/api/action.php',{method:'POST',body:new URLSearchParams({action:'ready',player_token:playerToken})});const d=await r.json();toast(d.message||'Position confirmée');await fetchState();}
fetchState();poll=setInterval(fetchState,1500);
</script></body></html>
