<?php
require_once __DIR__.'/../config/config.php'; start_app_session();
if(empty($_SESSION['player_game_id'])) redirect('/game/login.php');
$gid=(int)$_SESSION['player_game_id'];$st=db()->prepare('SELECT g.*,s.title FROM games g JOIN stories s ON s.id=g.story_id WHERE g.id=?');$st->execute([$gid]);$game=$st->fetch(PDO::FETCH_ASSOC);if(!$game)redirect('/game/login.php');
$pid=current_player_id($gid);$pq=db()->prepare('SELECT name,role_key,seat,ready FROM players WHERE id=? AND game_id=?');$pq->execute([$pid,$gid]);$me=$pq->fetch(PDO::FETCH_ASSOC)?:[];$roles=player_role_definitions();$role=$me['role_key']&&isset($roles[$me['role_key']])?$roles[$me['role_key']]:null;
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#05070b"><title>RT ESCAPE · Boîte aux lettres</title><link rel="stylesheet" href="/assets/app.css"></head><body class="player-mailbox-page"><main class="player-shell"><div id="idle" class="player-idle"><img src="/assets/rt-escape-player-idle.png" alt="RT ESCAPE"><div class="player-idle-overlay"></div><div class="player-idle-content"><img src="/assets/rt-escape-logo.png" class="player-idle-logo" alt="RT ESCAPE"><span class="eyebrow">BOÎTE AUX LETTRES INTERACTIVE</span><h1>EN ATTENTE D'UNE TRANSMISSION</h1><p>Le maître du jeu pilote votre mission en direct.</p><div class="player-status" id="conn">● CONNECTÉ</div></div></div><section id="active" class="player-active hidden"><header class="player-active-head"><img src="/assets/rt-escape-logo.png" alt="RT ESCAPE"><div><span class="eyebrow">TRANSMISSION DU MAÎTRE DU JEU</span><strong id="playerName"><?=e($me['name']??'Joueur')?></strong></div><span id="onlineDot">● LIVE</span></header><div id="roleCard" class="role-card"><span class="eyebrow">IDENTITÉ</span><h2><?=e($role['label']??'RÔLE EN ATTENTE')?></h2><p><?=e($role['seat']??'Le maître du jeu va attribuer votre identité.')?></p></div><div id="messages"></div><div class="player-actions"><button onclick="requestHint()">💡 DEMANDER UN INDICE</button><button class="primary" onclick="sendAnswer()">✍️ J'AI LA RÉPONSE</button><button onclick="requestAck()">✓ J'AI REÇU</button></div></section></main><script>
const token=<?=json_encode((string)($_SESSION['player_token']??''))?>;let source=null,lastId=0,items=[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function render(){const active=document.getElementById('active'),idle=document.getElementById('idle');if(!items.length){idle.classList.remove('hidden');active.classList.add('hidden');return;}idle.classList.add('hidden');active.classList.remove('hidden');document.getElementById('messages').innerHTML=items.map(m=>{let media='';if(m.media_url&&m.type==='image')media=`<img class="player-media" src="${esc(m.media_url)}">`;else if(m.media_url&&m.type==='video')media=`<video class="player-media" autoplay playsinline controls src="${esc(m.media_url)}"></video>`;else if(m.media_url)media=`<a class="player-doc" href="${esc(m.media_url)}" target="_blank">📄 OUVRIR LE DOCUMENT</a>`;return `<article class="player-message"><span class="eyebrow">${esc(m.title||'TRANSMISSION')}</span><p>${esc(m.body||'')}</p>${media}<small>${esc(m.created_at||'')}</small></article>`}).join('');}
async function sync(){try{const r=await fetch('/api/mailbox.php?player_token='+encodeURIComponent(token),{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.ok){items=d.messages||[];render();}}catch(e){}}
async function post(action,body=''){const r=await fetch('/api/mailbox.php',{method:'POST',body:new URLSearchParams({action,body,player_token:token})});const d=await r.json();if(d.ok)sync();}
function requestHint(){post('hint_request');}function requestAck(){post('ack','Le joueur confirme avoir reçu la transmission.');}function sendAnswer(){const v=prompt('Votre réponse :');if(v!==null&&v.trim())post('answer',v.trim());}
function connect(){try{source=new EventSource('/api/live.php?channel=player&player_token='+encodeURIComponent(token));source.addEventListener('refresh',sync);source.onerror=()=>{source.close();setTimeout(connect,1500);};}catch(e){setTimeout(connect,1500);}}sync();connect();
</script></body></html>
