<?php
require_once __DIR__.'/../config/config.php'; start_app_session();
if(empty($_SESSION['player_game_id'])) redirect('/game/login.php');
$st=db()->prepare("SELECT g.*,s.title,s.subtitle,s.slug FROM games g JOIN stories s ON s.id=g.story_id WHERE g.id=?"); $st->execute([$_SESSION['player_game_id']]); $game=$st->fetch(PDO::FETCH_ASSOC); if(!$game) redirect('/game/login.php');
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($game['title'])?> — RT ESCAPE</title><link rel="stylesheet" href="/assets/app.css"></head>
<body class="game-ui rttf-ui"><header class="game-top"><div class="game-logo">RT <span>ESCAPE</span></div><div class="mission">DOSSIER <strong id="stage">01</strong> / 05</div><div class="timer-wrap"><small>FENÊTRE TEMPORELLE</small><div class="timer" id="timer">--:--</div></div></header>
<main class="game-main"><section class="scientist"><div class="avatar" id="avatar">⚡</div><div><span class="eyebrow" id="eyebrow">TRANSMISSION ENTRANTE</span><h1 id="title">ANOMALIE TEMPORELLE DÉTECTÉE</h1><p id="story">La ligne temporelle est instable.</p></div></section>
<section class="game-panel"><div class="progress"><i id="progress"></i></div><div id="mission-content" class="mission-content"></div></section></main>
<div class="evidence-modal hidden" id="evidenceModal"><div class="evidence-card"><button class="close-x" onclick="closeEvidence()">×</button><div id="evidenceBody"></div></div></div>
<div class="modal hidden" id="answerModal"><div class="answer-card time-terminal"><span class="eyebrow">TERMINAL DE SYNCHRONISATION</span><div class="terminal-screen"><small>DESTINATION / CODE DE RETOUR</small><strong id="answerDisplay">_ _ _ _ _ _ _ _ _ _</strong></div><p id="answerPrompt">La fenêtre temporelle se referme. Entrez le code sur le clavier de la machine.</p><div class="keypad" id="keypad"></div><button class="btn primary terminal-submit" onclick="submitTerminal()">⚡ ENVOYER À LA MACHINE</button><div id="answerMessage" class="answer-message"></div></div></div>
<div class="toast hidden" id="toast"></div>
<script>
let state=null,poll=null,lastStage=0,modalForced=false,terminalValue='';
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function fmt(sec){sec=Math.max(0,Number(sec)||0);return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
async function fetchState(){const r=await fetch('/api/state.php',{cache:'no-store'});if(r.status===410){document.body.innerHTML='<main class="join"><section class="join-card"><span class="eyebrow">ACCÈS COUPÉ</span><h1>Vous avez été retiré</h1><p>L’organisateur a fermé votre accès à cette timeline.</p><a class="btn primary" href="/game/login.php">REJOINDRE UNE AUTRE PARTIE</a></section></main>';clearInterval(poll);return;}if(!r.ok)return;const d=await r.json();if(!d.ok)return;state=d.game;render();}
function render(){
 if(!state)return; const stage=Number(state.stage);document.getElementById('stage').textContent=String(stage||1).padStart(2,'0');document.getElementById('timer').textContent=fmt(state.stage_remaining);document.getElementById('progress').style.width=(stage/5*100)+'%';document.getElementById('timer').classList.toggle('danger',state.stage_remaining<=60);
 if(stage!==lastStage){lastStage=stage;modalForced=false;terminalValue='';}
 if(!stage){document.getElementById('title').textContent='EN ATTENTE DU DÉPART';document.getElementById('story').textContent='Le professeur prépare la machine. Restez près du terminal.';document.getElementById('mission-content').innerHTML='<div class="waiting cinematic-wait"><div class="flux-ring">⚡</div><h2>CHRONOLOGIE EN VEILLE</h2><p>Lorsque le chronomètre démarrera, le laboratoire s’ouvrira.</p><div class="scanline"></div></div>';return;}
 if(state.status==='finished'&&stage===5&&state.response_value){document.getElementById('title').textContent='TIMELINE RESTORED';document.getElementById('story').textContent='La ligne temporelle est stabilisée.';document.getElementById('mission-content').innerHTML='<div class="finale cinematic-finale"><div class="lightning-burst">⚡</div><h2>MISSION ACCOMPLIE</h2><p>88 MPH · 1.21 GW · DESTINATION VALIDÉE</p><strong>BON ANNIVERSAIRE LÉANE !</strong><div class="finale-date">HILL VALLEY · 1985</div></div>';return;}
 const m=state.mission;if(!m)return;document.getElementById('eyebrow').textContent=m.eyebrow;document.getElementById('title').textContent=m.title;document.getElementById('story').textContent=m.intro;
 const found=new Set(state.discoveries||[]);let html=renderScene(stage,m,found);if(state.hint)html+='<div class="hint-box cinematic-hint"><strong>MESSAGE DU PROFESSEUR</strong><p>'+esc(state.hint)+'</p></div>';if(state.answer_revealed)html+='<div class="revealed-answer cinematic-reveal"><span>LE PROFESSEUR A TRANSMIS LE CODE</span><strong>'+esc(state.revealed_answer)+'</strong></div>';if(state.response_required)html+='<button class="force-answer cinematic-answer-btn" onclick="openAnswer()">⚡ ACTIVER LE TERMINAL DE RÉPONSE</button>';document.getElementById('mission-content').innerHTML=html;if(state.response_required&&!modalForced)openAnswer();}
function sceneHeader(label,text,found,total){return `<div class="scene-header"><div><span class="eyebrow">${label}</span><h2>${text}</h2></div><div class="found film-counter">${found} / ${total} indices</div></div>`}
function hotspot(key,icon,title,found){return `<button class="scene-hotspot ${found?'found':''}" onclick="inspect('${key}')"><span class="hot-icon">${icon}</span><b>${title}</b><small>${found?'INDICE RÉCUPÉRÉ':'EXAMINER'}</small></button>`}
function renderScene(stage,m,found){
 const n=(m.objects||[]).length;
 if(stage===1)return sceneHeader('SCÈNE 01 · HILL VALLEY 1985','LE LABORATOIRE DU PROFESSEUR',found.size,n)+`<div class="rttf-scene lab-cinematic"><div class="room-title">TEMPORAL RESEARCH LAB · 1985</div><div class="window-1955">HILL VALLEY<br><strong>1955</strong><span>→</span><b>1985</b></div><div class="wall-clock">${hotspot('clock','🕐','HORLOGE',found.has('clock'))}</div><div class="filing-cabinet">${hotspot('files','📁','DOSSIERS TOP SECRET',found.has('files'))}</div><div class="radio-console">${hotspot('radio','📻','RADIO TEMPORALE',found.has('radio'))}</div><div class="computer-console">${hotspot('console','🖥️','CONSOLE',found.has('console'))}</div><div class="lab-bench"><span>FLUX CAPACITOR — PROTOTYPE</span><i></i><i></i><i></i></div><div class="lab-cables"></div><div class="scene-grain"></div></div><div class="scene-tip">Cherchez les objets comme dans une vraie pièce. Les indices peuvent être cachés dans les détails.</div>`;
 if(stage===2)return sceneHeader('SCÈNE 02 · ARCHIVES','LES ARCHIVES DE HILL VALLEY',found.size,n)+`<div class="rttf-scene archive-cinematic"><div class="archive-sign">HILL VALLEY<br><strong>COUNTY ARCHIVES</strong><small>RESTRICTED · TEMPORAL INCIDENTS</small></div><div class="archive-wall"><div class="newspaper-stack">${hotspot('newspaper','📰','JOURNAUX',found.has('newspaper'))}</div><div class="photo-board">${hotspot('photo','📸','PHOTO',found.has('photo'))}</div><div class="archive-drawer">${hotspot('archive','🗃️','DOSSIER 1955',found.has('archive'))}</div></div><div class="archive-floor"></div></div><div class="scene-tip">Observez les dates, les photographies et les documents. Une anomalie ne devrait pas exister.</div>`;
 if(stage===3)return sceneHeader('SCÈNE 03 · TRANSMISSION','LA RADIO TEMPORELLE',found.size,n)+`<div class="rttf-scene radio-cinematic"><div class="radio-wall"><div class="frequency-display">88.7 <small>MHz</small></div><div class="waveform">∿∿∿∿∿∿∿∿∿</div><div class="tuner-dial" onclick="tuneRadio()">◉<span>88</span><span>89</span><span>90</span></div></div><div class="radio-clues"><div>${hotspot('signal','📡','SIGNAL',found.has('signal'))}</div><div>${hotspot('dial','🎚️','CADRAN',found.has('dial'))}</div><div>${hotspot('tape','🎞️','BANDE',found.has('tape'))}</div></div><div class="radio-glow"></div></div><div class="scene-tip">Réglez la fréquence, écoutez les impulsions et retrouvez le dernier chiffre.</div>`;
 if(stage===4)return sceneHeader('SCÈNE 04 · MACHINE','LA DELOREAN',found.size,n)+`<div class="rttf-scene delorean-cinematic"><div class="dashboard"><div class="dashboard-label">TIME CIRCUIT CONTROL</div><div class="time-circuits"><div><small>DESTINATION</small><strong>1985</strong></div><div><small>DATE</small><strong>10·26</strong></div><div><small>TIME</small><strong>21:00</strong></div></div><div class="flux-capacitor">⚡</div><div class="dashboard-lights"><i></i><i></i><i></i><i></i><i></i></div></div><div class="delorean-clues"><div>${hotspot('year','⌛','ANNÉE',found.has('year'))}</div><div>${hotspot('date','📅','DATE',found.has('date'))}</div><div>${hotspot('time','⏱️','HEURE',found.has('time'))}</div></div><div class="windshield">HILL VALLEY · NIGHT</div></div><div class="scene-tip">La DeLorean attend sa destination. Vérifiez chaque paramètre avant de lancer le passage.</div>`;
 return sceneHeader('SCÈNE 05 · FINALE','LE FLUX CAPACITOR',found.size,n)+`<div class="rttf-scene finale-cinematic"><div class="power-core"><div class="core-ring"></div><div class="core-value">1.21 <small>GW</small></div><div class="core-status">FLUX INSTABLE</div></div><div class="speedometer"><strong>88</strong><small>MPH</small></div><div class="final-switches"><button onclick="pulseCore()">⚡ FLUX</button><button onclick="pulseCore()">🚗 VITESSE</button><button onclick="pulseCore()">🔋 CAPACITOR</button></div><div class="finale-clues"><div>${hotspot('flux','⚡','FLUX',found.has('flux'))}</div><div>${hotspot('speed','🚗','VITESSE',found.has('speed'))}</div><div>${hotspot('capacitor','🔋','FLUX CAPACITOR',found.has('capacitor'))}</div></div></div><div class="scene-tip">Trois paramètres. Une seule synchronisation. Stabilisez la machine avant la rupture.</div>`;
}
async function inspect(key){const body=new URLSearchParams({key,stage:String(state.stage)});const r=await fetch('/api/discover.php',{method:'POST',body});const d=await r.json();if(d.ok){state.discoveries=[...(state.discoveries||[]),d.key].filter((v,i,a)=>a.indexOf(v)===i);openEvidence(d);render();}}
function openEvidence(d){const body=document.getElementById('evidenceBody');body.innerHTML=`<span class="eyebrow">ARCHIVE RÉCUPÉRÉE</span><div class="evidence-object">${esc(d.title)}</div><p>${esc(d.text)}</p><div class="evidence-fragment"><small>FRAGMENT TEMPORAL</small><strong>${esc(d.clue)}</strong></div><div class="evidence-stamp">TEMPORAL RESEARCH · 1985</div>`;document.getElementById('evidenceModal').classList.remove('hidden');}
function closeEvidence(){document.getElementById('evidenceModal').classList.add('hidden')}
function buildKeypad(){const k=document.getElementById('keypad');k.innerHTML='';for(let i=1;i<=9;i++)k.innerHTML+=`<button onclick="keyPress('${i}')">${i}</button>`;k.innerHTML+=`<button class="clear" onclick="keyClear()">CLR</button><button onclick="keyPress('0')">0</button><button class="back" onclick="keyBack()">⌫</button>`;}
function keyPress(v){if(terminalValue.length>=12)return;terminalValue+=v;updateDisplay()}
function keyClear(){terminalValue='';updateDisplay()}
function keyBack(){terminalValue=terminalValue.slice(0,-1);updateDisplay()}
function updateDisplay(){document.getElementById('answerDisplay').textContent=(terminalValue||'_').padEnd(10,'_').split('').join(' ')}
function openAnswer(){buildKeypad();terminalValue='';updateDisplay();document.getElementById('answerModal').classList.remove('hidden');modalForced=true}
async function submitTerminal(){if(!terminalValue)return;const body=new URLSearchParams({stage:String(state.stage),answer:terminalValue});const r=await fetch('/api/answer.php',{method:'POST',body});const d=await r.json();const box=document.getElementById('answerMessage');box.textContent=d.message||'';box.className='answer-message'+(d.correct?'':' error');if(d.correct){document.getElementById('answerModal').classList.add('hidden');toast(d.finished?'TIMELINE RESTORED !':'COORDONNÉES VALIDÉES !');modalForced=false;await fetchState();}}
function tuneRadio(){toast('88.7 MHz — SIGNAL VERROUILLÉ');}
function pulseCore(){toast('Flux capacitor : synchronisation en cours…')}
fetchState();poll=setInterval(fetchState,1500);
</script></body></html>
