<?php
require_once __DIR__.'/../config/config.php';
$code=strtoupper(trim($_GET['code']??''));
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RT ESCAPE · SALLE</title><link rel="stylesheet" href="/assets/app.css"></head><body class="room-screen cinematic-room"><div id="screen"></div><script>
const code=<?=json_encode($code)?>;let lastEvent='';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=s=>{s=Math.max(0,Number(s)||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
const eventText={boarding:['ÉQUIPAGE EN ATTENTE','Prenez place. Le voyage n’a pas encore commencé.'],story_start:['ET SI NOUS REMONTIONS LE TEMPS ?','Écoutez le maître du jeu. La DeLorean va reprendre vie.'],lights:['SYSTÈMES D’ALIMENTATION','Les instruments du tableau de bord s’allument progressivement.'],engine:['MOTEUR PRÊT','La DeLorean attend les dernières consignes.'],anomaly:['ANOMALIE TEMPORELLE','Quelque chose vient de traverser la ligne temporelle. Observez.'],coordinates:['COORDONNÉES DÉTECTÉES','Les informations recueillies par l’équipage commencent à converger.'],prepare_jump:['PRÉPAREZ-VOUS','Le Flux Capacitor entre en charge.'],jump:['ACCROCHEZ-VOUS','VOYAGE TEMPOREL EN COURS…'],reset_scene:['SYSTÈMES STABILISÉS','La DeLorean revient en attente.']};
async function poll(){const r=await fetch('/api/public_state.php?code='+encodeURIComponent(code),{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.ok)render(d.game)}
function render(g){const crew=g.crew||[],ready=crew.filter(x=>Number(x.ready)).length,ev=g.gm_event||'boarding',txt=eventText[ev]||eventText.boarding;if(ev!==lastEvent){lastEvent=ev;document.body.classList.remove('event-flash');void document.body.offsetWidth;document.body.classList.add('event-flash');}
let html=`<div class="cinema-top"><b>RT <span>ESCAPE</span></b><span>HILL VALLEY · 1985</span><strong>${fmt(g.stage_remaining)}</strong></div><div class="delorean-cinema"><div class="windshield-cinema"><div class="rain-lines"></div><div class="hill-sign">HILL VALLEY</div><div class="road-cinema"><i></i><i></i><i></i></div></div><div class="dashboard-cinema"><div class="gauge-cinema"><b>${ev==='jump'?'88':'0'}</b><small>MPH</small></div><div class="flux-cinema ${ev==='jump'?'flux-on':''}"><div class="flux-core">⚡</div><span>FLUX CAPACITOR</span><b>${ev==='jump'?'1.21 GW':ev==='prepare_jump'?'CHARGING':'OFFLINE'}</b></div><div class="time-circuit-cinema"><small>TIME CIRCUIT</small><b>${ev==='coordinates'?'10 · 26 · 1985':'-- · -- · ----'}</b><b>${ev==='coordinates'?'21:00':'--:--'}</b></div></div><div class="dash-detail left-detail">DMC-12<br><small>CONNECTION: OK</small></div><div class="dash-detail right-detail">EQUIPAGE<br><small>${ready} / ${crew.length} EN PLACE</small></div></div><div class="cinema-message"><span>${esc(txt[0])}</span><h1>${esc(txt[1])}</h1><div class="crew-mini">${crew.map(x=>`<div class="crew-mini-item ${Number(x.ready)?'on':''}"><i></i>${esc(x.name)}<small>${esc(x.seat||'')}</small></div>`).join('')}</div></div>`;
if(ev==='jump')html+=`<div class="jump-overlay"><div>88 MPH</div><small>ACCROCHEZ-VOUS…</small></div>`;
document.getElementById('screen').innerHTML=html;}
poll();setInterval(poll,700);
</script></body></html>