<?php
require_once __DIR__.'/../config/config.php';
$code=strtoupper(trim($_GET['code']??''));
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#02060a"><title>RT ESCAPE · ÉCRAN SALLE</title><link rel="stylesheet" href="/assets/app.css"></head><body class="room-screen room-generic"><div id="screen"></div><script>
const code=<?=json_encode($code)?>;
let lastStage=-1,lastEvent='',lastSolved=false;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=s=>{s=Math.max(0,Number(s)||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
const pct=(n,d)=>d?Math.min(100,Math.round(n/d*100)):0;
const eventText={boarding:['ÉQUIPAGE EN ATTENTE','Prenez place. Le voyage n’a pas encore commencé.'],story_start:['ET SI NOUS REMONTIONS LE TEMPS ?','Écoutez le maître du jeu. La mission commence.'],lights:['SYSTÈMES D’ALIMENTATION','Les instruments de la machine s’allument.'],engine:['MOTEUR PRÊT','La salle attend les dernières consignes.'],anomaly:['ANOMALIE TEMPORELLE','Observez les détails. Quelque chose ne correspond pas.'],coordinates:['COORDONNÉES DÉTECTÉES','Les informations de l’équipage commencent à converger.'],prepare_jump:['CHARGE DU FLUX','La machine entre en phase de préparation.'],jump:['SAUT TEMPOREL','ACCROCHEZ-VOUS…'],reset_scene:['SYSTÈMES STABILISÉS','La scène revient à son état initial.']};
async function poll(){try{const r=await fetch('/api/public_state.php?code='+encodeURIComponent(code),{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.ok)render(d.game);}catch(e){}}
function shell(g,body,tag='ÉCRAN SALLE'){
 const crew=g.crew||[],ready=crew.filter(x=>Number(x.ready)).length,ev=g.gm_event||'boarding',txt=eventText[ev]||eventText.boarding;
 return `<div class="room-top"><div class="room-brand">RT <span>ESCAPE</span></div><div class="room-tag">${tag}</div><div class="room-clock">${fmt(g.stage_remaining)}</div></div><div class="room-stagebar"><span>ÉTAPE ${String(g.stage||0).padStart(2,'0')} / 05</span><i><b style="width:${pct(g.stage||0,5)}%"></b></i><span>${ready} / ${crew.length} EN PLACE</span></div>${body}<div class="room-footer"><span>${esc(txt[0])}</span><b>${esc(txt[1])}</b><div class="room-crew">${crew.map(x=>`<span class="room-crew-item ${Number(x.ready)?'ready':''}"><i></i>${esc(x.name)}</span>`).join('')}</div></div>`;
}
function render(g){
 const stage=Number(g.stage||0),ev=g.gm_event||'boarding',solved=!!g.puzzle_solved;
 if(stage!==lastStage||ev!==lastEvent||solved!==lastSolved){lastStage=stage;lastEvent=ev;lastSolved=solved;document.body.classList.remove('room-pulse');void document.body.offsetWidth;document.body.classList.add('room-pulse');}
 let body='';
 if(!stage){body=renderWaiting(g);}
 else if(stage===1){body=renderDeLorean(g);}
 else if(stage===2){body=renderArchives(g);}
 else if(stage===3){body=renderRadio(g);}
 else if(stage===4){body=renderCircuit(g);}
 else if(stage===5){body=renderFlux(g);}
 document.getElementById('screen').innerHTML=shell(g,body);
 if(ev==='jump')document.getElementById('screen').insertAdjacentHTML('beforeend','<div class="room-jump"><strong>88 MPH</strong><span>SAUT TEMPOREL EN COURS</span></div>');
}
function renderWaiting(g){const crew=g.crew||[],ready=crew.filter(x=>Number(x.ready)).length;return `<main class="room-wait"><div class="wait-orbit"><div class="wait-core">⚡</div></div><span class="room-eyebrow">PRÉPARATION DE LA MISSION</span><h1>PRENEZ PLACE</h1><p>Chaque joueur rejoint la partie sur son téléphone.<br>Lorsque tout l’équipage est en place, le maître du jeu lance l’aventure.</p><div class="wait-progress"><b style="width:${pct(ready,crew.length)}%"></b></div><strong>${ready} / ${crew.length} JOUEURS PRÊTS</strong></main>`}
function renderDeLorean(g){const ev=g.gm_event||'boarding',active=['lights','engine','anomaly','coordinates','prepare_jump','jump'].includes(ev);return `<main class="room-scene room-delorean"><div class="room-sky"><div class="hill-valley-room">HILL VALLEY</div><div class="road-room"><i></i><i></i><i></i></div><div class="road-glow"></div></div><div class="delorean-dashboard-room"><div class="room-gauge"><b>${ev==='jump'?'88':'0'}</b><small>MPH</small></div><div class="room-flux ${active?'active':''}"><div>⚡</div><span>FLUX CAPACITOR</span><b>${ev==='jump'?'1.21 GW':ev==='prepare_jump'?'CHARGING':active?'ONLINE':'OFFLINE'}</b></div><div class="room-timecircuit"><small>TIME CIRCUIT</small><b>${ev==='coordinates'?'10 · 26 · 1985':'-- · -- · ----'}</b><strong>${ev==='coordinates'?'21:00':'--:--'}</strong></div></div><div class="room-help-card"><span>MISSION EN SALLE</span><b>Observez la machine et écoutez le maître du jeu.</b><small>Les informations importantes peuvent apparaître ici. Les actions et réponses restent sur les téléphones.</small></div></main>`}
function renderArchives(g){const p=g.puzzle||{},opened=Object.keys(p.opened||{}).length,ok=(p.timeline_ok?1:0)+(p.photo_ok?1:0);return `<main class="room-scene room-puzzle"><div class="puzzle-title"><span>ÉPREUVE 02 · OBSERVATION</span><h1>LES ARCHIVES DE HILL VALLEY</h1><p>La salle peut aider : observez les documents affichés et confrontez-les avec ce que vous trouvez.</p></div><div class="archive-wall"><div class="archive-card ${opened>=1?'seen':''}"><span>📰</span><b>JOURNAL</b><small>UNE · DATE · ÉVÉNEMENT</small></div><div class="archive-card ${opened>=2?'seen':''}"><span>📸</span><b>PHOTOGRAPHIE</b><small>DÉTAIL À OBSERVER</small></div><div class="archive-card ${opened>=3?'seen':''}"><span>🗃️</span><b>ARCHIVE</b><small>NUMÉRO · CHRONOLOGIE</small></div></div><div class="room-puzzle-status"><div><span>DOSSIERS CONSULTÉS</span><strong>${opened} / 3</strong></div><div><span>CHRONOLOGIE</span><strong>${p.timeline_ok?'VALIDÉE':'À DÉCODER'}</strong></div><div><span>PHOTOGRAPHIE</span><strong>${p.photo_ok?'VALIDÉE':'À OBSERVER'}</strong></div></div><div class="room-instruction">🔎 <b>REGARDEZ L’ÉCRAN</b><span>Les téléphones servent aux manipulations individuelles. La salle fournit les informations communes.</span></div></main>`}
function renderRadio(g){const p=g.puzzle||{},freq=Number(p.freq||0);return `<main class="room-scene room-puzzle"><div class="puzzle-title"><span>ÉPREUVE 03 · MUSIQUE & LOGIQUE</span><h1>LA RADIO TEMPORELLE</h1><p>Un signal traverse la salle. Les joueurs travaillent sur leurs téléphones pendant que l’écran expose le signal commun.</p></div><div class="radio-console-room"><div class="radio-dial"><div class="dial-ring"></div><strong>${freq?freq.toFixed(1):'88.0'}</strong><small>MHz</small></div><div class="radio-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="radio-display"><span>TRANSMISSION</span><b>${p.morse_ok?'SIGNAL SYNCHRONISÉ':'SIGNAL INSTABLE'}</b><small>${p.tape_ok?'BANDE LUE':'BANDE À DÉCODER'}</small></div></div><div class="signal-hint-room"><b>ÉCOUTEZ · OBSERVEZ · PARTAGEZ</b><span>Le maître du jeu peut utiliser le son de la salle pour compléter cette épreuve.</span></div></main>`}
function renderCircuit(g){const p=g.puzzle||{},v=k=>esc(p[k]??'--');return `<main class="room-scene room-puzzle"><div class="puzzle-title"><span>ÉPREUVE 04 · MANIPULATION</span><h1>TIME CIRCUIT</h1><p>La destination se règle sur les téléphones. L’écran affiche l’état collectif de la machine.</p></div><div class="circuit-board-room"><div class="circuit-cell ${p.year_ok?'ok':''}"><small>YEAR</small><strong>${v('year')}</strong><i>${p.year_ok?'✓ LOCKED':'WAITING'}</i></div><div class="circuit-cell ${p.month_ok?'ok':''}"><small>MONTH</small><strong>${v('month')}</strong><i>${p.month_ok?'✓ LOCKED':'WAITING'}</i></div><div class="circuit-cell ${p.day_ok?'ok':''}"><small>DAY</small><strong>${v('day')}</strong><i>${p.day_ok?'✓ LOCKED':'WAITING'}</i></div><div class="circuit-cell ${p.hour_ok?'ok':''}"><small>HOUR</small><strong>${v('hour')}:${v('minute')}</strong><i>${p.hour_ok&&p.minute_ok?'✓ LOCKED':'WAITING'}</i></div></div><div class="ignition-room"><span>SÉQUENCE DE DÉPART</span><b>${p.ignition_ok?'ARMÉE':'EN ATTENTE'}</b><small>${(p.ignition||[]).join(' → ')||'POWER → BRAKE → LAUNCH'}</small></div></main>`}
function renderFlux(g){const p=g.puzzle||{},power=Number(p.power||0),speed=Number(p.speed||0);return `<main class="room-scene room-puzzle room-finale"><div class="puzzle-title"><span>ÉPREUVE 05 · FINALE</span><h1>STABILISER LE FLUX</h1><p>Toute la salle voit les paramètres collectifs. Chaque joueur conserve ses commandes sur son téléphone.</p></div><div class="flux-board-room"><div class="flux-meter"><small>PUISSANCE</small><strong>${power}</strong><span>/ 121 GW</span><i><b style="width:${pct(power,121)}%"></b></i></div><div class="capacitor-room ${p.switch_ok?'live':''}"><div>⚡</div><b>FLUX</b><small>${p.switch_ok?'SYNCHRONISÉ':'EN ATTENTE'}</small></div><div class="flux-meter"><small>VITESSE</small><strong>${speed}</strong><span>/ 88 MPH</span><i><b style="width:${pct(speed,88)}%"></b></i></div></div><div class="final-room-status">${g.puzzle_solved?'◉ FLUX STABILISÉ · MISSION ACCOMPLIE':'◌ SYNCHRONISATION EN COURS'}</div></main>`}
poll();setInterval(poll,700);
</script></body></html>
