<?php
require_once __DIR__.'/../config/config.php'; require_admin();
$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT g.*,s.title,s.subtitle,s.slug FROM games g JOIN stories s ON s.id=g.story_id WHERE g.id=?");$s->execute([$id]);$g=$s->fetch(PDO::FETCH_ASSOC);if(!$g)redirect('/admin/index.php');
$p=db()->prepare("SELECT * FROM players WHERE game_id=? ORDER BY id");$p->execute([$id]);$players=$p->fetchAll(PDO::FETCH_ASSOC);
$content=game_content($g['slug']);$stage=(int)$g['current_stage'];$stageRemain=($g['stage_ends_at']&&$g['status']==='running')?max(0,strtotime($g['stage_ends_at'])-time()):0;$currentAnswer=($stage&&isset($content[$stage]))?$content[$stage]['answer']:null;$answerShown=$stage>0?answer_revealed($id,$stage):false;
$joinUrl=APP_URL.'/game/login.php?code='.rawurlencode($g['code']);$qr='https://api.qrserver.com/v1/create-qr-code/?size=300x300&margin=12&data='.rawurlencode($joinUrl);
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="8"><title>Partie <?=e($g['code'])?></title><link rel="stylesheet" href="/assets/app.css"></head><body class="admin"><header class="admin-top"><div class="brand">RT <span>EVENTS</span> / ESCAPE</div><a href="/admin/index.php">← Tableau de bord</a><a class="btn" target="_blank" href="/game/screen.php?code=<?=e(rawurlencode($g['code']))?>">📺 ÉCRAN SALLE</a></header><main class="admin-wrap">
<section class="control-hero"><div><span class="eyebrow">PARTIE <?=e($g['status'])?></span><div class="big-code"><?=e($g['code'])?></div><p><?=e($g['title'])?> · <?=$g['duration']?> min · <?=e($g['difficulty'])?> · <?=e($g['mode'])?> · Variante <?=e($g['variant'])?></p></div><div class="control-actions"><form method="post" action="/admin/game_action.php"><input type="hidden" name="id" value="<?=$id?>"><?php if($g['status']==='running'): ?><button name="action" value="pause" class="btn">Ⅱ PAUSE</button><?php else: ?><button name="action" value="start" class="btn primary">▶ DÉMARRER</button><?php endif; ?><button name="action" value="add_time" class="btn">+5 MIN</button><button name="action" value="hint" class="btn">💡 INDICE</button><button name="action" value="force_response" class="btn">⚠ RÉPONSE</button><button name="action" value="next" class="btn">→ ÉTAPE SUIVANTE</button><button name="action" value="finish" class="btn danger">■ TERMINER</button><button name="action" value="reset" class="btn danger">↻ RESET</button><button name="action" value="delete_game" class="btn danger" onclick="return confirm('Supprimer définitivement cette partie et tous ses joueurs ?')">🗑 SUPPRIMER</button></form></div></section><section class="admin-card gm-events"><div class="live-title"><div><span class="eyebrow">MAÎTRE DU JEU</span><h2>Événements salle · Épreuve 1</h2></div><span class="muted">Déclenche les effets pendant ta narration</span></div><div class="gm-event-grid"><form method="post" action="/admin/game_action.php"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="gm_event"><button name="event" value="story_start" class="btn primary">🎬 COMMENCER L’HISTOIRE</button><button name="event" value="lights" class="btn">💡 ALLUMER LES SYSTÈMES</button><button name="event" value="engine" class="btn">🔑 DÉMARRER LE MOTEUR</button><button name="event" value="anomaly" class="btn">⚠ ANOMALIE TEMPORELLE</button><button name="event" value="coordinates" class="btn">📍 COORDONNÉES</button><button name="event" value="prepare_jump" class="btn">⚡ CHARGER LE FLUX</button><button name="event" value="jump" class="btn danger">🚗 SAUT TEMPOREL</button><button name="event" value="reset_scene" class="btn">↺ RÉINITIALISER LA SCÈNE</button></form></div></section>
<section class="admin-grid"><section class="admin-card qr-card"><span class="eyebrow">CONNEXION JOUEURS</span><h2>Scannez pour rejoindre</h2><img class="qr" src="<?=e($qr)?>" alt="QR Code de la partie"><div class="join-code"><?=e($g['code'])?></div><p class="muted">Les joueurs saisissent ensuite leur prénom. Tu pilotes tout depuis cette page.</p></section>
<section class="admin-card"><div class="live-title"><div><span class="eyebrow">PILOTAGE</span><h2>Épreuve <?=$stage?> / 5</h2></div><div class="admin-clock"><?=sprintf('%02d:%02d',intdiv($stageRemain,60),$stageRemain%60)?></div></div><div class="admin-progress"><i style="width:<?=min(100,$stage/5*100)?>%"></i></div><?php if($stage&&isset($content[$stage])):?><h3><?=e($content[$stage]['title'])?></h3><p><?=e($content[$stage]['intro'])?></p><div class="admin-answer"><div><span class="eyebrow">RÉPONSE ATTENDUE</span><strong><?=e($currentAnswer)?></strong></div><form method="post" action="/admin/game_action.php"><input type="hidden" name="id" value="<?=$id?>"><?php if($answerShown): ?><button name="action" value="hide_answer" class="btn">🙈 CACHER AUX JOUEURS</button><span class="answer-state visible">AFFICHÉE AUX JOUEURS</span><?php else: ?><button name="action" value="reveal_answer" class="btn primary">👁 AFFICHER AUX JOUEURS</button><span class="answer-state">CACHÉE</span><?php endif; ?></form></div><?php else:?><p>En attente du lancement.</p><?php endif;?></section></section>
<section class="admin-card"><div class="table-head"><h2>Joueurs connectés <span class="player-count">👥 <?=count($players)?></span></h2><span class="muted"><?php $readyCount=count(array_filter($players,fn($x)=>(int)($x['ready']??0)===1)); ?><?=count($players)?><span> équipiers · <?=$readyCount?> prêts</span> · Actualisation automatique</span></div><div class="players"><?php foreach($players as $pl):?><div class="player-chip"><span><i></i><?=e($pl['name'])?> <small><?=e($pl['seat']??'')?></small></span><form method="post" action="/admin/game_action.php" onsubmit="return confirm('Retirer ce joueur de la partie ?')"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="player_id" value="<?=$pl['id']?>"><button name="action" value="delete_player" title="Retirer">×</button></form></div><?php endforeach;if(!$players):?><em>Scannez le QR code pour faire apparaître les joueurs.</em><?php endif;?></div></section>
<section class="admin-card"><h2>Contrôle direct</h2><form method="post" action="/admin/game_action.php" class="stage-form"><input type="hidden" name="id" value="<?=$id?>"><label>Aller à l'étape<select name="stage"><?php for($i=0;$i<=5;$i++):?><option value="<?=$i?>" <?=$stage===$i?'selected':''?>><?=$i?> / 5</option><?php endfor;?></select></label><button name="action" value="stage" class="btn primary">APPLIQUER</button></form></section>
</main></body></html>
