<?php
require_once __DIR__.'/../config/config.php'; require_admin();
$stories=db()->query("SELECT * FROM stories WHERE active=1 ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
$games=db()->query("SELECT g.*,s.title,(SELECT COUNT(*) FROM players p WHERE p.game_id=g.id) player_count FROM games g JOIN stories s ON s.id=g.story_id ORDER BY g.id DESC LIMIT 30")->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="20"><title>Admin — RT ESCAPE</title><link rel="stylesheet" href="/assets/app.css"></head><body class="admin">
<header class="admin-top"><div class="header-brand"><img class="rt-escape-logo compact-logo" src="/assets/rt-escape-logo.png" alt="RT ESCAPE — RT EVENTS"><span class="brand-context">MAÎTRE DU JEU</span></div><div><span>Connecté : <?=e($_SESSION['admin_user'])?></span> <a href="/admin/logout.php">Déconnexion</a></div></header>
<main class="admin-wrap"><div class="admin-head"><div><span class="eyebrow">CENTRE DE CONTRÔLE</span><h1>Préparer une partie</h1><p>Crée la partie, affiche son QR code puis pilote toute l'expérience depuis ici.</p></div></div>
<section class="admin-card"><form method="post" action="/admin/create_game.php" class="create-form"><label>Scénario<select name="story_id"><?php foreach($stories as $s): ?><option value="<?=$s['id']?>"><?=e($s['title'])?></option><?php endforeach;?></select></label><label>Durée<select name="duration"><option value="20">20 min — Express</option><option value="30" selected>30 min — Classique</option><option value="45">45 min — Long</option><option value="60">60 min — Expert</option></select></label><label>Difficulté<select name="difficulty"><option value="easy">Facile</option><option value="normal" selected>Normal</option><option value="hard">Difficile</option><option value="expert">Expert</option></select></label><label>Mode<select name="mode"><option value="local">Local</option><option value="connected">Connecté</option></select></label><label>Variante<select name="variant"><option>A</option><option>B</option><option>C</option></select></label><button class="btn primary">CRÉER LA PARTIE</button></form></section>
<section class="admin-card"><div class="table-head"><h2>Parties</h2><span class="muted">Actualisation automatique</span></div><div class="table"><?php foreach($games as $g): ?><div class="row"><div><strong class="code"><?=e($g['code'])?></strong><span><?=e($g['title'])?> · <?=$g['duration']?> min · <?=e($g['difficulty'])?> · <?=e($g['mode'])?> · Variante <?=e($g['variant'])?></span></div><div><span class="player-count">👥 <?=$g['player_count']?></span><span class="status <?=$g['status']?>"><?=e($g['status'])?></span><a class="small-btn" href="/admin/game.php?id=<?=$g['id']?>">Gérer</a><form method="post" action="/admin/game_action.php" style="display:inline" onsubmit="return confirm('Supprimer définitivement cette partie et tous ses joueurs ?')"><input type="hidden" name="id" value="<?=$g['id']?>"><button name="action" value="delete_game" class="small-btn danger-link">Supprimer</button></form></div></div><?php endforeach; if(!$games): ?><p>Aucune partie préparée.</p><?php endif;?></div></section>
</main></body></html>
